version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/public:/var/www/public 
    depends_on:
      - app

  app:
    build: .
    volumes:
      - ./app:/var/www
    ports:
      - "9000"