version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravelsaas
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
